name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # apna VM jahan runner install hai

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Replace old JAR with new one
        run: |
          $targetJar = Get-ChildItem -Path "target" -Filter "*.jar" | Select-Object -First 1
          Copy-Item -Path $targetJar.FullName -Destination "C:\Springboot\pdfspeech\app.jar" -Force

      - name: Restart Windows Service
        run: |
          Stop-Service PdfToAudioService
          Start-Service PdfToAudioService
